MAGE_START="!mageraid"
MAGE_SIPHONED="!siphoned"
MAGE_OUTCOME="!outcome"
UMBASAM = "!umbasam"

CASTLE_START="!castleraid"

REACT_SUCCESS = "⚔️"
REACT_FAILED = "☠️"
REACT_DELETE = "❌"
REACT_CARAVAN = "🏇"

REACT_ROLE_MDPS = "🗡️"
REACT_ROLE_RDPS = "🏹"
REACT_ROLE_TANK = "🛡️"
REACT_ROLE_SUPP = "🔮"
REACT_ROLE_HEAL = "✳️"