UMBASAM_QUOTES = [
    "DA NEKS LEBEL PLAY",
    "PATAY KUNG PATAY!!",
    "TARA REDTREE? O ANO?",
    "*INCOHERENT LAUGHTER*",
    "HALIKA DITO MAY 2M KA SAKEN",
    "UBE",
    "SINO SI TALENTADONG PEPENG TUMATAMBLING?",
    "AY WALANJO"
]

UMBASAM_CTA = [
    "PATAY KUNG PATAY!! JOIN CTA COMMS NOW!",
    "TIME FOR NEKS LEBEL PLAY! JOIN CTA COMMS NOW!",
    "WE MASS UP NOW! SHOW WHAT OATHBREAKERS ARE MADE OF!",
    "DON'T LET THE SHOTCALLERS DOWN! SHOW UP! TIME FOR CTA!",
]