UMBASAM_QUOTES = [
    "DA NEKS LEBEL PLAY",
    "PATAY KUNG PATAY!!",
    "TARA REDTREE? O ANO?",
    "*INCOHERENT LAUGHTER*",
    "HALIKA DITO MAY 2M KA SAKEN",
    "UBE",
    "SINO SI TALENTADONG PEPENG TUMATAMBLING?",
    "AY WALANJO"
]